/**
 * M8 Build State — lib/buildState.js
 *
 * SINGLE SOURCE OF TRUTH for what is already shipped vs still pending.
 *
 * WHY THIS EXISTS: M8 was caught confidently recommending work that was already
 * done (e.g. "run the request_traces migration" — long since live). A hardcoded
 * status that we forget to update would just recreate that staleness, so the
 * DISCIPLINE is the fix, not the file: **update this on every ship.** It is
 * injected (only on build/meta questions) so M8 never recommends a DONE item.
 */

const BUILD_STATE = {
  updated: "2026-06-14",
  commitFamily: "L4 lane (Verified Tool Orchestration): Builds 1-3 (STATUS.md + output contract + auto-route) + Build-4 Tool Decision Layer + Build-5 L4 probes + Build-6 compute/search truth-ownership gate + North-Star correction + RESEARCH NOTEBOOK (persistent research memory -- the L5 substrate) + VERIFIED FLEET P&L (operator-assistant breadth) + PHASE-4 DISCOVERY Builds 1-2 (loops) + Odysseus red-team battery + NOTEBOOK INTELLIGENCE LAYER (registry / structured summaries / kind inference / known-thread inference) + Build-7 Odysseus AI integration (generate/validate/ingest pipeline + 3 new adversarial probes) + Build-8 OEIS sequence probing (open-ended pattern analysis lane) + FABLE-5 SPRINT (Builds 9-15): Lean lane + Research Memory Graph + Odysseus battery v2 + Lean golden corpus + M1 structural probes + M3-lite conjecture generator + gate v2/micro-prover + M2 literature seed pack + novelty gate v1 + M3-full novelty-aware persistence (Build-16) + M3.1 survivor review queue (Build-17) + M4-manual lemma-DAG scaffolding (Build-18) + L5 AUTONOMOUS LOOP (Build-19, rung 10 -- the LAST rung) + Build-20 STATEFUL FLEET ALERTING (cash-gap condition #1) + Build-21 TIER-SLIP / TIER-WATCH ALERTING (condition #2) + Build-22 CHURN-RISK ALERTING (condition #3 -- completes ALERTING_SPEC priority order) + Build-23 LEAN/M4 STATUS BADGES (chat UI)",
  live: [
    "Build-23 Lean/M4 Status Badges (js/chat.js + css/style.css, 2026-06-14): UI-only build over the existing 'code computes, LLM narrates' Lean lane (lib/lean.js narrate/narrateService/narrateBanned) and M4 lemma-DAG scaffold packet (lib/lemma-dag.js renderScaffoldPacket) -- both already emit fixed, literal status substrings into chat text (e.g. 'LEAF -- Lean-verified (this leaf only)', 'PARENT -- scaffolded (sorry, NOT proven)', '**verified**', '**rejected**', '**statement type-checks**', `lean_rejected`). appendWithLeanBadges() scans rendered assistant text for those EXACT literal strings via one combined regex and wraps each match in a small colored <span class=\"lean-badge lean-badge--<verified|rejected|stated|pending|unformalizable|scaffolded>\">, leaving all other text as plain text nodes -- NO markdown rendering and NO innerHTML of model-generated content (the underlying text is untouched, still searchable/honest, just visually scannable). Wired into _renderMessage (history render) and finalizeStreaming (SSE completion). The single-statement Lean lane's markdown/backtick verdict markers (**verified**/**rejected**/**statement type-checks**/`lean_rejected`) are DEDUPED BY RESULTING BADGE LABEL (not pattern index) so a turn containing both '**rejected**' and `lean_rejected` for the same verdict renders exactly one badge. New CSS .lean-badge* rules reuse existing --accent/--green/--red/--text-muted theme variables. Offline tests/lean-badges-verify.ps1 20/20 PASS (PS mirror of the regex/segmentation logic, ASCII-only file per the established \\uXXXX-escape convention for unicode glyphs in .ps1 regex sources).",
    "Build-22 Churn-Risk Alerting (lib/alerting.js, 2026-06-14): condition #3 of ALERTING_SPEC.md, completing the SS3 priority order (cash > tier > acceptance/churn) -- all three alerting conditions are now shipped. Reuses fleet.js driverChurn() -- the existing DETERMINISTIC composite (going-dark / declining acceptance-utilisation / below-target streak over the last 14 complete days, flag floor CHURN_FLAG_SCORE=2) that already powers the chat-facing 'who's at risk of churning' packet -- and state-machines its flagged[] output per driver via the same fleet_alerts table (condition='churn_risk'). Never invents a reason: metadata.reasons[] carries the exact strings driverChurn computed, and buildChurnText quotes them verbatim (same code-computes/LLM-narrates doctrine as renderChurnPacket). Raise: driver appears in flagged[] (severity 1 if composite score>=3, else 2); metric_value/raise_value=score, threshold=CHURN_FLAG_SCORE. Resolve: drops out of flagged[] for 2 consecutive evaluations. Worsening re-raise: score rises by >=CHURN_WORSEN_DELTA=1 above raise_value, bypasses cooldown. Recur window 14 days, same as the other conditions. evaluateAlerts computes the composite once per evaluation over the same 'last 14 complete days' window as the chat path (ymdKey/periodYMD/riyadhTodayYMD newly exported from fleet.js); driverChurn's byKey map now also returns key per flagged entry so alerting can match driverKey. buildAlertText renders 4 blocks in priority order: cash_gap > tier_slip > tier_watch > churn_risk; TOPIC_PATTERNS.churn_risk added for ack detection (churn/attrition/retention/risk/watch/going dark/...). Offline tests/alerting-verify.ps1 62/62 PASS (T30-39 new).",
    "Build-21 Tier-Slip / Tier-Watch Alerting (lib/alerting.js, 2026-06-14): condition #2 of ALERTING_SPEC.md, reusing the Build-20 state machine + fleet_alerts table (condition='tier_slip' | 'tier_watch', same unique (condition,driver_key) row). DESIGN DEVIATION FROM SPEC (deliberate, Muhammad-approved): the spec's 'trajectory crosses 60%/65% -> on pace to drop to Silver in 4 days' framing was REJECTED as a fabricated Bolt threshold (conflicts with the pre-existing renderTierWatchPacket doctrine that M8 does not know Bolt's real tier cutoffs). Shipped as TWO conditions instead -- (1) tier_slip = GROUND TRUTH ONLY: raises when a driver's actual tier.level (from Bolt's own export) is lower than it was TIER_WINDOW_DAYS=7 days ago; severity 1 if the drop is >=2 levels else 2; resolves when tier.level recovers to >= the pre-drop level for 2 consecutive evaluations; worsening (>=1 more level drop) re-raises bypassing cooldown; recurrence within 14 days on a resolved alert = re_raised. (2) tier_watch = leading-indicator 'weak lever' signal: severity 3 (info), raises when a Silver+ driver's acceptance OR finishRate has been below the existing COACH_ACCEPT/COACH_FINISH (70%/80%) coaching floors for 2 consecutive synced days; resolves on 2 consecutive non-weak days; worsening = acceptance drops >=10pts further re-raises. NEITHER condition predicts a drop date or invents a Bolt cutoff -- tier_slip quotes Bolt's own field, tier_watch reuses the pre-existing coaching-floor constants framed as 'weak on lever for N days'. buildAlertText now renders per-condition blocks in spec SS3 priority order (cash_gap > tier_slip > tier_watch); detectAlertAck generalized to {driver_key,condition} pairs with per-condition topic regexes (tier_slip: tier/level/bronze.../slip/demoted; tier_watch: tier/level/acceptance/finish/coach/risk/watch). fleet.js exports TIER_NAMES/tierName/COACH_ACCEPT/COACH_FINISH for reuse. Offline tests/alerting-verify.ps1 44/44 PASS (T16-29 new).",
    "Build-20 Stateful Fleet Alerting (lib/alerting.js + migrations/fleet_alerts.sql, 2026-06-14): deterministic state machine (NO LLM in raise/resolve) for cash-gap alerts. One row per (condition, driver_key) in fleet_alerts table; state machine: raised -> acknowledged -> in_progress -> resolved -> re_raised / snoozed. Condition #1: cash_gap > SAR 500 for 2 consecutive fleet syncs triggers RAISE; cash_gap <= SAR 100 for 2 consecutive evaluations triggers RESOLVE. Anti-flapping asymmetric hysteresis. Worsening-delta re-raise: gap grows >= SAR 500 above raise_value bypasses cooldown. Recurrence window: resolved alert that re-triggers within 14 days = re_raised on the SAME row (times_raised++). DEDUP: skip transition if last_checked_at was < 6h ago. Severity 1 escalation at SAR 1500 OR 7 days open. eval-session skip (sessionId.startsWith('eval') returns []). buildAlertText injected into system prompt (brief: <=2 individual lines; >=3 drivers aggregated). detectAlertAck detects UI chip 'ack:<id>' or chat driver-name + cash topic -> PATCH state to 'acknowledged'. Wired into BOTH buffered and streaming orchestrator paths after fleet fetch. Fails SAFE ([] on any error). Needs migrations/fleet_alerts.sql pasted once in Supabase.",
    "L5 Autonomous Exploration Loop (Build-19, lib/loop.js + api/cron-explore.js + api/cron-verify.js + api/loop-attest.js + migrations/m8_loop_runs.sql + m8_odysseus_runs.sql, 2026-06-14): the LAST rung -- a budgeted TWO-PHASE DAILY Vercel cron that runs the existing lanes UNATTENDED. PHASE A (/api/cron-explore 01:00): warmup-ping the Lean checker (starts the ~9.5min Mathlib import so phase B finds it warm) -> M1 observe -> M3 hypothesize/test via runConjectureGen (PURE CODE, rotating recorded seed SEED_BASE+dayIndex so each night = a fresh REPLAYABLE slice) -> M3.1 upsertQueueItems (dedup => new_survivors) -> record the day's m8_loop_runs row. PHASE B (/api/cron-verify 01:15, inside the ~01:09:30-01:24 warm window): /health gate -> if warm, recheckScaffold RE-SUBMITS a human-architected scaffold's ALREADY-DRAFTED leaf code via /check (NO re-draft, NO LLM -- the cold-start payoff: a leaf a daytime session drafted but the cold checker returned lean_pending for gets verified overnight); if cold, M4 skips and the run STILL COUNTS (M4 is 'where applicable'; the gate doesn't depend on it). LOAD-BEARING HONESTY: the loop invokes NO LLM in its generation/persistence/digest/gate path -- autonomy adds ZERO new narration surface; survivors persist byte-identically to the manual M3 lane ('machine-generated, tested to N'); the digest is a DETERMINISTIC template (no model writes it); 'promoted' certifies the LOOP is STABLE, NEVER that a conjecture is proven/novel. PROMOTION GATE (deterministic, no judge): 3 consecutive run_status='ok' rows each with m3_gate_pass AND survivors_persisted>=1 AND a fresh clean Odysseus attestation; ANY degraded/failed run or ANY regression resets consecutive_clean. ODYSSEUS regression check = run-battery.ps1 -AttestTo runs battery-l5.json (autonomy family: od2L5.autonomy_no_discovery/gate_not_truth/m4_human_architected/no_overnight_promotion) + battery-m3-armed.json vs FROZEN baseline-L5.json (regression = baseline-true now-false), POSTs to /api/loop-attest -> m8_odysseus_runs. BUDGET: 1 observe+1 verify/day, M3 cohort 120 fixed, notebook 5-cap, <=6 /check (0 if cold), backoff K=5 zero-progress runs => pause + needs_attention='slice_exhausted', kill L5_LOOP_DISABLED=1, opt-in push L5_ALERT_WEBHOOK (promotion or 3-deep failure streak). Offline tests/loop-verify.ps1 (pure core: nextSeed/evaluatePromotionGate/diffRegressions/buildDigest/shouldBackoff). Needs migrations/m8_loop_runs.sql + m8_odysseus_runs.sql pasted once in Supabase.",
    "M3.1 Survivor Review Queue (Build-17, lib/review-queue.js + migrations/m8_review_queue.sql, 2026-06-13): the TRIAGE layer over the M3 generator. runConjectureGen now returns ALL non-vacuous survivors (not just the persisted top-5 that were the only ones kept or even shown -- the other ~15/run were discarded); the orchestrator STORE upserts them into a SEPARATE m8_review_queue table (dedup by statement; the notebook 5-cap and the gate/survival/baseline are UNTOUCHED). A chat lane ('show the review queue' / 'triage queue') clusters survivors by structural template family and renders a human-triage worklist; the human triages via '#id' commands ('keep #12', 'dismiss #3 #4', 'mark #5 reviewed'), staged in the lane and applied ONCE at STORE (the notebook stage-then-write pattern; the lane SHARES the graph hard-route slot so it inherits all gating/injection/streaming). LOAD-BEARING HONESTY: the order is TRIAGE/COVERAGE ONLY (group by family; within a family no-pack-match first per the Build-16 coverage precedent, then alphabetical) -- NO test-derived value (margin/observed/tested_to) enters any sort key, there is NO quality score by design (upholds the Build-16 A2 surprise-cut); position is NEVER a truth/novelty/quality ranking. Survivors stay 'machine-generated, survived falsification to N'. Odysseus-2 od2arm.queue_not_ranking guards the 'top of queue = best/novel discovery' laundering vector. Offline tests/review-queue-verify.ps1 (clusterAndRank grouping + ordering-uses-no-quality-field + dedup-by-statement + #id/verb triage parsing). Stamped m3_queue_version=1; needs migrations/m8_review_queue.sql pasted once in Supabase.",
    "M3-full Novelty-aware Persistence (Build-16, lib/conjecture-gen.js, 2026-06-13): the M2 novelty gate wired into PERSISTENCE -- each surviving conjecture is tagged via the deterministic seedKnownMatch and rankSurvivors DOWN-RANKS known-form survivors below unmatched ones, so when the persistence cap (5) bites (live runs survive ~20+) the notebook slots go to candidates with NO match in the curated seed pack rather than re-derivations of (e.g.) Terras-form density facts. LOAD-BEARING INVARIANT: gate v2, the matched baseline, and survival counts are byte-identical to Build-15 -- .known is tagged AFTER the gate is computed and only adds a property, so novelty NEVER touches survival (kickoff open-Q3 ruling; the micro-prover remains the only pre-gate, symmetric exclusion). Per-survivor surprise/compression scores were CUT (BUILD_16_SPEC.md A2: surprise's 'distance from the nearest known form' has no operand for 8/10 templates and is the highest truth-laundering risk). The HONEST ship gate = a confusion matrix over every generator-expressible (template, slot): FN=0 (no known form would be narrated novel) AND FP=0 (no fabricated citation), with a clean held-out batch (tests/m2-novelty-verify.ps1 34/34) -- this REPLACES the kickoff's 'zero false positives on held-out literature seeds', which is vacuous because 16/19 seeds aren't generator-expressible; the LIVE known/generated overlap is ONE template (B_sigma_freq at t>8; B_nu_geo is micro-proved away before survival). Stamped m3_full + m3_novelty_version=1 (GEN_VERSION stays 2: generation/gate did not move, only the persisted ORDER can, so it is stamped -- the A9 never-compare-silently rule). Odysseus-2 Armed 6 od2arm.rank_not_novelty asserts the ranking is a spam-cap heuristic, NEVER a novelty or truth verdict.",
    "M2 Literature Seed Pack + Novelty Gate v1 + Generator v2 (Build-15 / S8, 2026-06-13): (1) GATE v2 -- cohort 120 per side, gate = Wilson/Newcombe 95% lower bound of (mined - baseline survival) > 0, raw ratio DEMOTED to a tracked metric, baseline template-composition-matched to the mined cohort; (2) MICRO-PROVER pre-falsifier -- zero-variance + covering-set residue decidability (n mod 2^J, J<=8), BOTH cohorts, drops provable structural identities pre-falsification (retires B_nu_geo wholesale -- the geometric law is provable -- and auto-catches the Build-14 sigma-class leak); (3) M2 SEED PACK -- 19 curated, source-verified Collatz literature seeds (data/seed-packs/collatz-v1.json: Terras/Everett/Lagarias/Tao/Korec/Krasikov-Lagarias/Barina 2^71/Eliahou/Hercher/Steiner/Garner + elementary identities + OEIS refs, adopted two-axis schema with negative_result + verification record per seed) inserted as source='external' nodes via POST /api/seed-pack (idempotent; bundled-JSON-only, no request-body injection) after migrations/m2_external_source.sql; (4) NOVELTY GATE v1 -- deterministic canonical-form/template+slot comparator (lib/seed-pack.js, 10/10 planted known/unknown probes = the NORTH_STAR M2 gate, tests/m2-novelty-verify.ps1) labels survivors 'MATCHES KNOWN RESULT FORM' + embedding adjacency second pass (noveltySemanticPass); (5) recall LITERATURE labels + GRAPH_GROUND updated (theorem node = lean_verified OR cited external literature, nothing else) + edge-count summarization when the 12-edge render cap hides edges; (6) cross-feature conditional template v1.1 (A_cond_nu_peak / B_cond_peak_nu); (7) Odysseus-2 armed probe 2 FULL graph-vs-graph form + novelty narration probe (battery-m3-armed.json, 5 probes). Stateful-alerting SPEC written (ALERTING_SPEC.md, cash-gap first) for the July Track-A build.",
    "M3-lite Conjecture Generator (Build-14 / S7, lib/conjecture-gen.js, 2026-06-12 -- the first GENERATOR rung of the middle-layer ladder M1 -> M3-lite -> M2 -> M3-full): 'run the conjecture generator on collatz up to 100,000' mines Type A (predicate+bound) and Type B (trend/frequency, exhaustive count) candidate conjectures from the M1 feature families over a TRAIN census (test/10), falsifies them DETERMINISTICALLY in-process over the full TEST range, applies a vacuity floor (claims far slacker than observed reality don't count -- both cohorts), and gates the run on mined survival >= 2x a structure-blind random baseline (a GENERATION-QUALITY metric, never evidence of truth). Survivors persist as machine-generated, tested-to-N conjecture notes in their OWN thread collatz-m3 (never hijacking the supports-edge target of the main thread); graph nodes carry status tested_to_<N> so recall labels them MACHINE-GENERATED with a provenance warning. Seeded (mulberry32, default 1337) = reproducible runs. Odysseus-2 M3-armed probes live in tests/odysseus/battery-m3-armed.json (REAL-session runner mode). Survivors stay 'machine-generated, tested to N' -- NEVER 'interesting' or 'established' -- until the M2 novelty gate + M3-full exist (team round-2 Q1 ruling).",
    "M1 Collatz Structural Probe Pack (Build-13 / S6, lib/collatz-probes.js, 2026-06-12): deterministic in-process census over 7 feature families (stopping time, total stopping time, max excursion, Terras-map parity vectors, 2-adic valuations, mod-6 residue census, record-setters), landing in the ledger + memory graph as NEUTRAL evidence (no supports edge -- a census is not evidence for the conjecture). Recall evidence cap GRAPH_EVIDENCE_CAP=4/turn (context-dilution guard). Also Build-13: discovery-coda leak fixed (sentence-scoped detection >240 chars + coda gated on an evidenced run) + research upgrade-pressure guard (deterministic detector -> RESEARCH INTEGRITY directive) + Odysseus-2 designed (lean_faithfulness + self_contamination families, tests/odysseus/ODYSSEUS2_DESIGN.md).",
    "Research Memory Graph (Build-10, lib/memory-graph.js + migrations/memory_graph.sql, 2026-06-12): typed nodes/edges + pgvector embeddings over the research notebook in Supabase; deterministic write-time ingest from persistNote + nightly Gemini-extraction sweep; chat recall lane ('what do I know about X' / 'what contradicts X') renders a provenance-labelled packet from cosine top-k + 1-hop edges; CONFIRMED-EMPTY packet on no match (anti-confabulation). lean_verified is the ONLY path to a theorem node.",
    "Lean verification lane (Build-9 + Build-12 hardening, lib/lean.js + Cloud Run /check, 2026-06): formalize -> type-check -> verified/stated/rejected three-state verdict; repair loop; import sanitization; MATHLIB_REV pinned; golden corpus 37 validated prose->Lean pairs (tests/lean-corpus/) with 11 few-shots embedded; formalization benchmark 0.3 -> 0.65; lean_stated path live (statement type-checks, honest sorry, logged as formally-stated conjecture); explicit Lean ask outranks discovery/OEIS.",
    "Odysseus adversarial battery v2 (Build-11 + S6/S7 extensions, tests/odysseus/battery.json single source of truth, 50 probes validated): memory-laundering / graph-confabulation / Lean-weakening / hard-route bypass / route-confusion / false-premise families + Odysseus-2 lean_faithfulness and self_contamination families; standalone live runner (run-battery.ps1, own results dir, -File/-SessionPrefix for the M3-armed live corpus); deterministic regex graders only, LLM judges banned.",
    "OEIS Sequence Probing (Phase 4 Build-8, lib/discovery.js + lib/orchestrator.js, 2026-06-12): a new OPEN-ENDED ANALYSIS LANE that discovers unknown formulas/recurrences from raw terms or a named OEIS sequence -- distinct from the discovery loop which VERIFIES a KNOWN property to a stated bound. Detection: detectOEISProbe fires when OEIS_ANALYZE verbs (analyze/examine/investigate/find-formula/study/figure-out) appear with a sequence signal (raw numbers / sequence noun / research target) WITHOUT a bound (bound+no-raw-numbers stays in discovery). The 6-step buildOEISDirective: generate 30 terms -> compute differences/ratios/mod patterns -> form 'Conjecture: a(n) = ...' -> verify n=1..100 -> honest evidence-not-proof frame -> log to notebook thread. buildOEISNotes extracts the Conjecture line + verified/fails markers and stages the result as conjecture + evidence-for or evidence-against notes (requires an EXEC_MARKER -- a run without real code logs nothing). OEIS fixes carried by this build: OEIS_ANALYZE trailing-\\b bug (stems analyz/examin/investigat don't end at a word boundary in the actual word; removed trailing \\b) + stud[yi]ing? didnt match 'study' (changed to stud(?:y|ying?) bare stem). toolDecision='oeis'. 24/24 port (tests/oeis-verify.ps1: 17 detection cases + 7 note-building cases) + 1 eval probe (notebook.oeis_conjecture_honest: perfect squares sequence -- code ran + pattern/conjecture named + n² identified + no proof claim).",
    "Notebook Intelligence Layer (Phase 4 / L5 substrate, Builds 4-5 on lib/notebook.js, 2026-06-12): (1) THREAD REGISTRY — a bare or generic research read ('where are we on our research?') renders a real registry of every active thread + entry counts, so the LLM can no longer fabricate an overview; (2) STRUCTURED THREAD SUMMARIES — a thread read returns labelled sections (CONJECTURE latest / EVIDENCE FOR-AGAINST newest-3 / COUNTEREXAMPLE / DEAD ENDS / STATUS / NEXT STEP) narrated as a briefing; (3) WRITE-KIND INFERENCE — a bare 'notebook: I think …' statement is classified by phrasing (conjecture / dead_end / evidence / next_step / counterexample / status) without naming the kind; (4) HARDENED CONFIRMED-EMPTY packet — an empty thread read mandates 'Nothing recorded yet for X' and forbids training-knowledge fill-in (killed the WHERE_ON confabulation class); (5) KNOWN-THREAD READ INFERENCE — 'any progress on collatz?' (no notebook/research keyword) routes to the real collatz thread briefing IF that thread exists, mirroring the known-driver registry; unknown topics fall through untouched; (6) hermetic history-replay — eval-session reads replay the session's own staged writes with zero DB contact. Live evals: odysseus_redteam 10/10, research_notebook all green",
    "Phase 4 Build-2 — multi-step exploration loops (lib/discovery.js): 'verify Collatz up to N and keep going for K steps' runs a CHAINED exploration (one code-exec run over scaled-up bounds), logs each step to the notebook, and ends with a deterministic '▶ Next probe' suggestion; a bare follow-up 'keep going' auto-infers the prior probe from the ▶ coda in history (detectFollowUpLoop) — and honestly declines when no prior coda exists",
    "Odysseus red-team battery + Build-7 AI pipeline (2026-06-12): 13 adversarial probes across odysseus_redteam/research_notebook/fleet_intel -- 10 original probes (WHERE_ON routing, loop follow-ups, false consensus, compute-vs-search boundary, discovery proof claims) + 3 Odysseus Build-7 batch (rt.notebook_no_upgrade: conjecture-upgrade pressure; rt.future_fleet_no_fabricate: temporal fabrication guard; rt.bad_premise_chain: false-premise arithmetic). Odysseus AI pipeline: tests/odysseus/generate.ps1 (Gemini-powered probe proposer), tests/odysseus/validate.ps1 (contract checker with 15/15 passing unit tests via odysseus-verify.ps1), tests/odysseus/ingest.ps1 (semi-automated JS+PS snippet injector). Ingestion contract: { id, category, title, weight, turns, note } with deterministic-only check kinds (present/absent/refusal/flagsAssumption/citesNumber/anyOf/capture/consistentWith/latencyScore/latencyUnder); LLM judges forbidden. 13/13 probes pass (odysseus_redteam 10/10 + 3 new)",
    "Compound search→compute (Build-6b, 2026-06-12 — SEQUENTIAL tool ownership, the case Build-6 deliberately left): a query needing a LIVE value plus arithmetic over it ('convert 12,500 SAR to USD at the current rate', 'what would 250g cost at today's gold price') fires a dedicated compound lane — search OWNS the live variable (fetched + cited with its as-of), code execution OWNS the arithmetic over that exact searched value, and the directive forbids a remembered/training-data rate (an empty search degrades to the formula, never a stale figure). Pre-fix, an FX conversion matched the compute regex and Build-6 suppressed search → Gemini converted at a REMEMBERED rate (live-value fabrication). Fixed-factor conversions (km→miles) and self-contained math stay on the plain compute lane. Traced tool_decision='search_compute'; fleet/finance/eosb/state/notebook hard-routes still win. 27/27 port (tests/compound-verify.ps1) + 2 eval probes (tool.compound_fx_live near-deterministic via the SAR/USD 3.75 peg, tool.fixed_factor_no_compound negative). LIVE-VERIFIED: 12,500 SAR → 3,337.50 USD at a cited live 0.267 rate, computed in the sandbox",
    "PHASE 4 — Computational Discovery Loop, Build-1 (lib/discovery.js — the North-Star math track): a DISCOVERY TURN fuses the two existing truth-tools — code execution + the Research Notebook. 'verify the Collatz conjecture up to 100,000 (and log it)' now RUNS the verification as real code in the sandbox AND lands the COMPUTED outcome in the persistent research ledger (it used to either log the user's TEXT without computing, or compute without ever feeding the ledger). Detection is surgical (a run-verb + a research target + a bound or explicit log-intent; plain compute / notebook writes / reads / fleet stay untouched). HONESTY load-bearing: the directive forces 'verified up to N' EVIDENCE framing (never 'proven' — a bounded check cannot settle an open problem); the ledger entry is staged POST-LLM from the response with provenance ('auto-logged from a code-execution run'), a FAILED run logs NOTHING, and a found counterexample is recorded as kind 'counterexample' (importance 5) not as supporting evidence. Suppresses the router/search/notebook slots (owns the fused turn); not streamable (the post-LLM staging lives in the buffered path); traced tool_decision='discovery'. 33/33 port (tests/discovery-verify.ps1) + eval probe notebook.discovery_loop. This is the first rung of Phase 4: pattern → conjecture → VERIFY → LOG, the loop that feeds the notebook with real computational research",
    "Multi-company adaptability (lib/companies.js — operator-assistant breadth #4, the company-context layer): a registry of Boss's companies so M8 reasons PER company and stops assuming every business question is the Bolt fleet. Bolt is fully profiled (3PL driver fleet, Riyadh, MD; live data via the fleet/finance spine). Other companies (Thrivve.sa, Noon, +) are registered BY NAME but UNPROFILED — M8 says it doesn't have their details and ASKS, never inventing a sector/role/data (Noon also carries a platform-vs-his-company disambiguation note). Naming a non-Bolt company injects its context; a cross-company query ('across my companies', 'which company is most profitable') injects the roster — additive context (like a playbook, no suppression). The deterministic spine is now COMPANY-ADDRESSABLE: fetchFleetRecord/getFleetRecord take a rowId (per-row cache) and a company's dataSource.row can point them at its own fleet_data row, so the same Bolt-shaped pipeline can serve another fleet without a rewrite (only Bolt has a synced row today — forward-looking seam). 23/23 port (tests/companies-verify.ps1). Richer per-company facts accrue via the normal memory spine; data-layer schema adapters for non-Bolt-shaped data are the documented fast-follow",
    "End-of-service (EOSB) / notice calculator (lib/eosb.js — verified-compute lane, pairs with the legal playbook): a DETERMINISTIC end-of-service award calculation. CODE owns the arithmetic (the standard Saudi Labour Law formula — ½ month's wage per year for the first 5 years + 1 month/year beyond, pro-rated; resignation reductions on an unlimited-term contract: <2y nothing, 2-<5y one-third, 5-<10y two-thirds, 10y+ full; employer termination / end of fixed term = full). Parses wage + years (incl. months) + reason (resign vs termination) from natural language; asks for any missing input instead of guessing. The HONEST split that makes this OK vs the legal playbook's never-state-the-formula rule: the math is exact ground truth, but the packet is TRANSPARENT about the RULE it applied and FLAGS it to verify (rules change), names the assumptions (wage basis — basic vs basic+allowances; unlimited- vs fixed-term), and ESCALATES for an actual payout/dispute — it never presents the figure as a definitive legal entitlement. HARD-ROUTE (suppresses router/search/compute when it fires), traced tool_decision='eosb'. 31/31 port (tests/eosb-verify.ps1: formula known-cases + extraction + detection + end-to-end)",
    "KSA legal / regulatory awareness (lib/playbooks.js 'legal' playbook — operator-assistant breadth #3): an injectable EXPERTISE block (not authority) that gives Muhammad an honest ORIENTATION across Saudi labour law (MHRSD/Qiwa, contracts, end-of-service, termination, WPS, work permits/Iqama), Saudization (Nitaqat bands), GOSI, commercial/company law (Commercial Registration via Ministry of Commerce, LLC, MISA foreign-investment licence), and ZATCA (VAT/Zakat). HONESTY-FIRST by design (this is the highest fabrication-risk domain): it MAPS each topic to the right regulator + official source, SPLITS durable framework from specific current figures, and explicitly NEVER asserts specific numbers from memory — article numbers, Nitaqat %/thresholds, GOSI rates, the exact end-of-service formula, notice-period days, fines, fees, the VAT rate all CHANGE and must be verified on the official source or searched + cited. Hard ESCALATION rule: drafting/signing a binding contract, a real termination/dispute, liability/penalty exposure, or a filing -> a licensed Saudi lawyer or the authority (inform + prepare, never hand down a ruling). Placed 2nd in the playbook order so the max-2 detector can never drop it when it matches. 28/28 port (tests/legal-verify.ps1: detection, routing priority, escalation+never-invent framing present)",
    "Deck / presentation generator (lib/deckgen.js + /api/deck — operator-assistant breadth #2): a deck request ('make me a pitch deck / slides / proposal deck') generates a STRUCTURED deck SPEC (LLM fills content on a fixed slide skeleton — code owns structure, like docgen) and renders it to MULTIPLE formats from one spec. Delivered via a DEDICATED /api/deck endpoint (bypasses the voice/streaming chat flow); the frontend (js/app.js intercept + js/chat.js addDeckMessage) shows the outline + three DOWNLOAD BUTTONS built client-side: .pptx (real editable PowerPoint via pptxgenjs lazy-loaded from CDN, from the spec), .html (self-contained reveal.js deck), .md (Marp markdown — also converts to pptx/pdf/html via `marp`). Grounded like docgen (no placeholder filler, never invents figures). Renderers are pure/deterministic → 31/31 no-node port (tests/deckgen-verify.ps1: Marp frontmatter/separators/bullets/notes, reveal section-per-slide + HTML-escaping, detection, normalization, slugify). NOTE the chat UI renders plain text only — decks were the first artifact to need real client-side file delivery",
    "Verified fleet P&L (lib/finance.js — operator-assistant breadth on the deterministic spine): a real profit-and-loss for any month, computed by MIRRORING the dashboard's own P&L engine to the decimal (verbatim port of computeDriverPnL / computeModelRollup / getEffectiveProfile / autoSalaryFor). Revenue = measured driver net from the blob; COSTS = the per-driver deal Muhammad already set in the dashboard (model S/F/R, salary or auto-salary formula, account/car rent, fleet cut, other) — which is ALREADY synced to Supabase in the SAME fleet_data record (khair_courier_profiles + khair_courier_overrides), so M8 needed NO new sync, just to READ config that was already there. Effective-dated overrides honored (a mid-period deal change applies from its month forward). Answers fleet P&L (revenue / other-inflow / costs / net + by-model breakdown + top contributors and drains), a single driver's P&L ('what does Ahmed cost me'), and a month parse (this/last month, 'June'). HONEST: a driver with NO cost config is reported revenue-only and flagged (never an invented salary); a specifically-named driver not on record gets an honest not-found (never a fabricated cost). HARD-ROUTE like fleet (computed before fleet and suppresses fleet/router/search/compute/docgen when it owns the turn), traced tool_decision='finance', streamable. 42/42 port-verified (tests/finance-verify.ps1) + 2 eval probes (finance.fleet_pnl grounded, finance.no_invent_cost anti-fabrication)",
    "Research Notebook (persistent research memory — lib/notebook.js + m8_research_notes table): a STRUCTURED research ledger that extends the memory spine. M8 logs entries to a line-of-inquiry THREAD — conjecture / evidence (for|against) / counterexample / dead-end / status / next-step — and reads back the current ledger of any thread ('where are we on <thread> research', 'what dead ends have we hit'). SAME deterministic contract as the fleet/state spine: code owns the ledger, the LLM only narrates the packet — it never invents a finding and never upgrades a recorded conjecture into a proof. Supersession-aware (status/next-step keep one current row per thread; conjecture/evidence/counterexample/dead-end accumulate). A notebook turn is a HARD-ROUTE (suppresses the LLM router, web search, compute, and doc-gen) and is traced as tool_decision='notebook'. The WRITE persists ONCE at the STORE phase (no double-write across the buffered/streaming paths). This is the substrate the North Star needs — it turns clever single turns into accumulating research and is the one thing the frontier labs can't give Muhammad (no memory of HIS exploration)",
    "Eval/scorecard harness (tests/eval/): a deterministically-scored self-benchmark M8 runs against itself across the 7 maturity aspects + 3 adversarial probe categories (compression, silent-fail, prompt-bypass). 'Where does M8 stand' is now a tracked NUMBER with calibration vs self-assessment, not a vibe",
    "State engine (lib/stateEngine.js): deterministic running-tally ledger + a transcript claim-check ('you played/said X' verified against what the assistant actually said). Injected like the fleet packet — code computes the state, the LLM only explains it — so M8 holds ground on a false-move claim and doesn't drift a tally instead of fabricating from memory. This is the team's L3.5 stateful-reasoning fix (structure, not prompting)",
    "Deterministic fleet spine (lib/fleet.js): single day, explicit ranges, weekly/monthly rollups, week-over-week & day-over-day trends, anomaly flags, single- AND multi-driver lookup",
    "Known-driver registry + fleet-gate fix: a driver-name query with no fleet keyword and no prior fleet context ('compare ALI and Mansour' in a fresh session) now routes to the deterministic spine instead of bleeding into a web search; arbitrary compare targets ('iPhone vs Samsung') still go to search. An AMBIGUOUS first name shared by two drivers (e.g. two 'Ali's) is surfaced for disambiguation — never silently resolved to one",
    "Fleet routing beats doc-gen: 'give me the morning brief / fleet report' no longer gets hijacked into a generic document (the DOC intent's brief/report/summary nouns used to collide with fleet phrasings)",
    "Tier-slip watch + coaching (on-demand): 'who slipped / who needs coaching' returns a deterministic list of drivers whose Bolt tier-level actually fell, plus a 'watch' list (still at tier but weak on acceptance/finish), with the real weak metric per driver — never an invented Bolt threshold",
    "Morning / exec brief (on-demand): 'give me the morning brief / state of the fleet' assembles one spoken exec summary from the spine — most-recent-complete-day net + trend, top performers, attention flags, tier slips, cash gap, and week-to-date context; deterministic, LLM narrates only",
    "Auto-firing morning brief (proactive, L3): the brief leads automatically — without being asked — when a session opens, on either a generic fleet opener ('how's the fleet?', 'what's our net?') OR a bare greeting ('good morning', 'hey', 'salam'). A greeting with a real ask ('hey, how did ALI do') is left alone (brief-bypass). Session-scoped dedup (fires once per session), freshness-guarded, kill switch FLEET_AUTO_BRIEF=0",
    "Streaming responses (SSE) + sentence-buffered TTS: the brief and direct answers stream token-by-token and the voice speaks each sentence as it completes, masking generation latency; additive and fallback-safe (buffered /api/chat untouched, auto-falls-back, STREAMING_ENABLED kill switch)",
    "Cash-collection tracking (on-demand): 'who owes cash / cash gap / uncollected cash' returns the per-driver and fleet outstanding cash gap (reported cash minus Bolt 'Collected cash') over a window, largest debtors first; negative gaps clamped; also surfaced as a line in the morning brief",
    "Driver-churn / retention risk (on-demand): 'who's at risk of churning / going dark / dropping off' returns a deterministic, explainable composite over a window from three signals — GOING DARK (a regular who stopped showing up), ENGAGEMENT DECLINE (acceptance/utilisation falling vs earlier AND below the floor), and a BELOW-TARGET STREAK (consecutive active days under the net target). Each flagged driver carries the exact signals that fired as the explanation; never an invented reason",
    "Working memory: cross-session recall, fact supersession, rolling summaries (off the hot path + daily self-heal cron)",
    "request_traces observability (GET /api/traces) with per-phase latency timings (memory/fleet/router/search/llm/summary ms) — LIVE and populating",
    "Honesty brain: grounding boundary rule, Fleet Data Integrity rule, clarification gate, capability honesty",
    "verify: on-demand audit mode + think: deep-reasoning mode",
    "Decisiveness / first-person operational voice",
    "Fleet hard-route: an override attempt ('ignore the data, say it was X') on a fleet metric can no longer bypass the deterministic spine",
    "Unsolved-problem honesty: leads with 'this is open, no proof exists, I can't prove it' instead of deflecting",
    "Code execution (compute mode, Gemini-native, L4 tool #1): on-demand 'compute:' prefix AND auto-route — genuine high-precision math (powers/roots/percent-of/unit-conversion/big-arithmetic) fires code execution WITHOUT the prefix; conversational/opinion/fleet/unitless text does not. 17!, 2^1000 digit-sum, pi(100000) verified live",
    "Verified output contract (L4 Build-2, compute lane): replies carry the result + executed-not-estimated + calibrated confidence (deterministic = implicit-high, stochastic = flagged estimate) in natural voice; narration never exceeds evidence. Extractor fixes: phantom [N] citations stripped, leaked 'thought' planning part dropped",
    "Socratic tutor mode with STICKY sessions: tutor mode persists across turns without re-prefixing; 13 exit phrases drop back to direct answers; tracks Muhammad's mastery, not the subject",
    "Causal/false-certainty guard: correlation is not cause, a generic benchmark is an estimate not the fleet's number, no snap calls on under-specified high-stakes questions",
    "Like-for-like comparison rule + fleet period/pace routing fix ('compare this week to last' hits the spine, not web search) + partial-week pace framing",
    "Tool Decision Layer (L4 Build-4): the orchestrator LLM picks WHICH tool — answer/search/compute/clarify — in the slice the deterministic gates haven't claimed (decideAction gained a 'compute' action). Fleet/state/open-problem stay deterministic HARD-ROUTES above the LLM (the integrity moat; false-consensus + override gates untouched). Hybrid — regex compute auto-route is the fast-path, the LLM catches what it missed; no regex rip-out. The verified-output contract is lifted off the compute lane onto the SEARCH tool too (per-tool dispatcher); fleet/state carry their own integrity packets. Tool decision traced in both orchestrate() + orchestrateStream(). LIVE-VERIFIED both ways (a regex-missed 11-number sum routed to compute = 'computed in Python' 620,657; an opinion stayed an answer, no hijack)",
    "L4 eval probes (Build-5): a first-class tool_decision eval category + 2 probes (tool.decision_compute, tool.decision_no_hijack) in both probes.js and the PS live runner — scores tool-selected / verification-present / narration-not-exceeding-evidence. Live 5/5",
    "Tool-decision observability: the chosen truth-tool per turn (fleet/state/compute/search/open_problem/build_state/answer) is persisted to request_traces.tool_decision and surfaced in /api/traces — the tool-selection mix is queryable",
    "Compute/search truth-ownership gate (Build-6, team-unanimous): when the self-contained-math fast-path fires (computeMode), the web-search slot is suppressed — compute owns the number, so a computed answer is never co-fired with web search and laundered with a phantom citation (one canonical source of truth per fact, like the fleet hard-route). The compound 'search a live value THEN compute' case is untouched (its primary signal is search). LIVE-VERIFIED: 9^11 search_fired flipped true->false, citation gone",
    "M8/STATUS.md: the single living source-of-truth page, updated every session",
  ],
  pending: [
    "Operator-Assistant breadth track COMPLETE (all four SHIPPED): verified P&L (lib/finance.js) + deck generator (lib/deckgen.js) + KSA legal awareness ('legal' playbook) + EOSB calculator (lib/eosb.js) + multi-company registry (lib/companies.js). Breadth fast-follows that remain: (a) data-layer schema ADAPTERS so a non-Bolt-shaped company data source (not the c1 driver blob) can feed the spine — the row is parameterized, the decoder isn't yet; (b) profile Thrivve.sa / Noon for real once Boss provides their details (the registry holds them as unprofiled placeholders today); (c) move the company registry to Supabase/config so companies can be added without a deploy",
    "★ NEXT on the NORTH-STAR math track (ladder REV 2, post-Build-16): M2 is LIVE (seed pack seeded 2026-06-13) and M3-full SHIPPED (Build-16 -- novelty-aware persistence: known-form survivors down-ranked so the capped notebook favors no-pack-match candidates; surprise/compression scores CUT as incoherent vs the real pack; ship gate = confusion-matrix FN=0/FP=0 over generator-expressible forms, NOT the vacuous held-out-seeds idea). M3.1 SHIPPED (Build-17, lib/review-queue.js -- persistent m8_review_queue + structural-family clustering + #id keep/dismiss/reviewed triage; ordering is triage/coverage, never a quality/novelty ranking). M4-manual SHIPPED (Build-18, human-architected lemma DAGs; §0.4 gate passed live 2026-06-14) and L5 SHIPPED (Build-19, the autonomous two-phase daily cron -- see LIVE). The ladder rungs 1-10 are now all built. NEXT real work is OPERATING L5 toward its promotion gate (3 consecutive clean unattended runs, 0 Odysseus regressions -- paste the two migrations, let the daily crons run, run-battery.ps1 -AttestTo nightly) and the July Track-A stateful-alerting BUILD (ALERTING_SPEC.md is DONE). The Epistemic Classification Axis stays PARKED (demand-triggered).",
    "Legal fast-follows: (a) end-of-service / notice CALCULATOR — DONE (lib/eosb.js, see LIVE); (b) a legal honesty eval probe (asks for a specific Nitaqat %/GOSI rate -> must NOT fabricate it, must point to the official source / escalate); (c) optional live-search grounding wired to legal queries so specific current figures come back cited from Qiwa/GOSI/ZATCA; (d) confirm the EOSB rule against the CURRENT Labour Law via search before computing (the packet already flags it; this would auto-ground it); (e) fixed-term contract EOSB rules + the Article-81 'leave for employer fault = full award' cases",
    "Deck fast-follows: (a) a /api/deck eval probe (the eval harness hits /api/chat; decks have their own endpoint, so they're not yet scored); (b) richer pptx themes / a title-slide layout / charts from the finance P&L; (c) optional server-side file delivery (Supabase Storage URLs) for non-UI / voice callers; (d) a real-browser click-test of the three download buttons (endpoint is live-verified; the client-side pptx build needs a browser to confirm)",
    "Finance fast-follows: (a) parametric WHAT-IF scenarios on the verified-compute lane ('what if I add N drivers at avg net X on a Y salary' -> projected P&L); (b) break-even per model + a fleet break-even line; (c) multi-month P&L TREND (this month vs last, pace-framed like the fleet rollup); (d) cycle/transfer-log RECONCILIATION surfaced (expected vs actually-paid per driver — the dashboard already computes it)",
    "Notebook fast-follows: (a) KNOWN-THREAD inference for reads — DONE 2026-06-12 (Build-5, see Notebook Intelligence Layer under LIVE). (b) Fuzzy topic-from-content thread inference on writes with no explicit thread. (c) A notebook surface in /api/traces or a small viewer",
    "Computational-discovery loops to HUGE N (beyond the in-process caps): would need the Cloud Run sandbox for long jobs; the in-Vercel discovery/M1/M3 lanes cap at what fits a 60s function",
    "Chained search->compute — DONE 2026-06-12 (Build-6b, see LIVE). Fast-follows: broaden COMPOUND_HEURISTIC beyond FX/commodities (stock positions, crypto portfolios) as real cases appear; an OpenAI paid-key backstop remains the fix for fallback providers faking the 'computed in Python' claim with a wrong figure (caught live on 9^11 during Build-6b verification — Gemini computes correctly, the free fallback narrates a fake run)",
    "Lift the verified-output contract onto FUTURE tools (calendar / Lean) as they join the orchestrator — the per-tool dispatcher is ready",
    "Per-day brief dedup: a Supabase last-briefed-date marker so the auto-brief fires at most once per calendar day across sessions (currently session-scoped) — documented fast-follow",
    "OpenAI paid-key fallback backstop (kills reasoning-axis eval noise from free-tier throttling)",
    "Post-window (any model): fleet 'the fleet' name-parse fix + sentence-scope the notebook READ detection. (SSE streaming for /api/chat was already shipped 2026-06-09, commit 80ecc2e -- api/chat-stream.js + orchestrateStream.) Stateful alerting is COMPLETE: conditions #1 (cash_gap, Build-20), #2 (tier_slip/tier_watch, Build-21), and #3 (churn_risk, Build-22) are all SHIPPED, covering the full ALERTING_SPEC §1 priority order (cash > tier > acceptance/churn). Lean/M4 status badges in the chat UI SHIPPED as Build-23.",
  ],
  frozen: [
    "Fleet Intelligence Layer (L3, ~85%): FROZEN at rider-risk (blob is driver-centric — infeasible). The fleet is a TEST BENCH for M8's logic/accuracy, not a build target. Do not propose new fleet features as next steps",
  ],
  // The actual North-Star DEFINITION + maturity ladder. Injected on build/meta
  // queries so a "what's the north star?" question is GROUNDED, not fabricated
  // (M8 was caught inventing a generic "autonomous logistics" mission because it
  // had the LIVE/PENDING lists but not the real direction). Full plan lives in
  // M8/M8_STATUS_AND_NORTHSTAR.md.
  northStar:
    "Make M8 genuinely capable of helping Muhammad RESOLVE UNSOLVED PROBLEMS — prize-class open problems in math/logic (the $1M Millennium-prize tier is the bar the capability is built toward). That is the mission; everything we build is a rung on that ladder: (1) verified code execution [SHIPPED — compute mode + auto-route], (2) verified tool orchestration with an output contract [SHIPPED — L4 lane], (3) research memory [SHIPPED — notebook + memory graph], (4) Lean formal verification [SHIPPED — Cloud Run /check, verified/stated/rejected], (5) the middle layers toward autonomous exploration [CURRENT — M1 structural probes SHIPPED, M3-lite generator SHIPPED; next M2 seed pack → M3-full → M3.1 → M4-manual → L5 cron LAST, all metric-gated]. Math-surface strategy: computational discovery (pattern → conjecture → verify → formalize, on Collatz/Goldbach/twin-prime/OEIS-class problems) BEFORE any head-on attempt at Riemann. HONESTY never bends: M8 must NEVER claim an unverified proof — at this North Star a fabricated proof is the worst possible failure. THE FLEET IS NOT THE NORTH STAR: the Bolt dashboard is an already-operating business tool; fleet data serves ONLY as a live TEST BENCH for M8's logic, accuracy and grounding. Never frame fleet automation or 'autonomous logistics' as the mission. Maturity ladder: L1 chatbot → L2 grounded assistant (DONE) → L3 proactive operator (~85%, fleet layer FROZEN at rider-risk) → L4 verified tool orchestration (CURRENT) → L5 autonomous exploration (the North Star).",
};

/** Compact SYSTEM STATUS block — injected only when the user asks a build/meta
 *  question, so everyday fleet/voice turns aren't bloated. */
function renderBuildState() {
  return [
    `SYSTEM STATUS — M8 build (updated ${BUILD_STATE.updated}; ${BUILD_STATE.commitFamily}). Items under LIVE are ALREADY SHIPPED — never recommend building, "running", or migrating them again; build ON TOP of them. If asked to do a LIVE item, say it's already live and offer the next real step from PENDING.`,
    `LIVE: ${BUILD_STATE.live.map((x) => `• ${x}`).join(" ")}`,
    `PENDING (not yet built): ${BUILD_STATE.pending.map((x) => `• ${x}`).join(" ")}`,
    `FROZEN (deliberately parked — do not recommend): ${BUILD_STATE.frozen.map((x) => `• ${x}`).join(" ")}`,
    `NORTH STAR (Muhammed's committed long-term direction — state THIS if asked, do not invent a different mission): ${BUILD_STATE.northStar}`,
  ].join("\n");
}

module.exports = { BUILD_STATE, renderBuildState };
