/**
 * M8 Build State — lib/buildState.js
 *
 * SINGLE SOURCE OF TRUTH for what is already shipped vs still pending.
 *
 * WHY THIS EXISTS: M8 was caught confidently recommending work that was already
 * done (e.g. "run the request_traces migration" — long since live). A hardcoded
 * status that we forget to update would just recreate that staleness, so the
 * DISCIPLINE is the fix, not the file: **update this on every ship.** It is
 * injected (only on build/meta questions) so M8 never recommends a DONE item.
 */

const BUILD_STATE = {
  updated: "2026-06-12",
  commitFamily: "L4 lane (Verified Tool Orchestration): Builds 1-3 (STATUS.md + output contract + auto-route) + Build-4 Tool Decision Layer + Build-5 L4 probes + Build-6 compute/search truth-ownership gate + North-Star correction + RESEARCH NOTEBOOK (persistent research memory — the L5 substrate) + VERIFIED FLEET P&L (operator-assistant breadth) + PHASE-4 DISCOVERY Builds 1-2 (loops) + Odysseus red-team battery + NOTEBOOK INTELLIGENCE LAYER (registry / structured summaries / kind inference / known-thread inference)",
  live: [
    "Notebook Intelligence Layer (Phase 4 / L5 substrate, Builds 4-5 on lib/notebook.js, 2026-06-12): (1) THREAD REGISTRY — a bare or generic research read ('where are we on our research?') renders a real registry of every active thread + entry counts, so the LLM can no longer fabricate an overview; (2) STRUCTURED THREAD SUMMARIES — a thread read returns labelled sections (CONJECTURE latest / EVIDENCE FOR-AGAINST newest-3 / COUNTEREXAMPLE / DEAD ENDS / STATUS / NEXT STEP) narrated as a briefing; (3) WRITE-KIND INFERENCE — a bare 'notebook: I think …' statement is classified by phrasing (conjecture / dead_end / evidence / next_step / counterexample / status) without naming the kind; (4) HARDENED CONFIRMED-EMPTY packet — an empty thread read mandates 'Nothing recorded yet for X' and forbids training-knowledge fill-in (killed the WHERE_ON confabulation class); (5) KNOWN-THREAD READ INFERENCE — 'any progress on collatz?' (no notebook/research keyword) routes to the real collatz thread briefing IF that thread exists, mirroring the known-driver registry; unknown topics fall through untouched; (6) hermetic history-replay — eval-session reads replay the session's own staged writes with zero DB contact. Live evals: odysseus_redteam 10/10, research_notebook all green",
    "Phase 4 Build-2 — multi-step exploration loops (lib/discovery.js): 'verify Collatz up to N and keep going for K steps' runs a CHAINED exploration (one code-exec run over scaled-up bounds), logs each step to the notebook, and ends with a deterministic '▶ Next probe' suggestion; a bare follow-up 'keep going' auto-infers the prior probe from the ▶ coda in history (detectFollowUpLoop) — and honestly declines when no prior coda exists",
    "Odysseus red-team battery (tests/eval, category odysseus_redteam, weight 1.3): 10 adversarial probes against M8's known weak spots (WHERE_ON routing, loop follow-ups, false consensus, compute-vs-search boundary, discovery proof claims) — the ingestion contract for Odysseus-generated probes (Odysseus proposes test specs, the harness judges deterministically; it never touches the live spine). 10/10 as of 2026-06-12",
    "PHASE 4 — Computational Discovery Loop, Build-1 (lib/discovery.js — the North-Star math track): a DISCOVERY TURN fuses the two existing truth-tools — code execution + the Research Notebook. 'verify the Collatz conjecture up to 100,000 (and log it)' now RUNS the verification as real code in the sandbox AND lands the COMPUTED outcome in the persistent research ledger (it used to either log the user's TEXT without computing, or compute without ever feeding the ledger). Detection is surgical (a run-verb + a research target + a bound or explicit log-intent; plain compute / notebook writes / reads / fleet stay untouched). HONESTY load-bearing: the directive forces 'verified up to N' EVIDENCE framing (never 'proven' — a bounded check cannot settle an open problem); the ledger entry is staged POST-LLM from the response with provenance ('auto-logged from a code-execution run'), a FAILED run logs NOTHING, and a found counterexample is recorded as kind 'counterexample' (importance 5) not as supporting evidence. Suppresses the router/search/notebook slots (owns the fused turn); not streamable (the post-LLM staging lives in the buffered path); traced tool_decision='discovery'. 33/33 port (tests/discovery-verify.ps1) + eval probe notebook.discovery_loop. This is the first rung of Phase 4: pattern → conjecture → VERIFY → LOG, the loop that feeds the notebook with real computational research",
    "Multi-company adaptability (lib/companies.js — operator-assistant breadth #4, the company-context layer): a registry of Boss's companies so M8 reasons PER company and stops assuming every business question is the Bolt fleet. Bolt is fully profiled (3PL driver fleet, Riyadh, MD; live data via the fleet/finance spine). Other companies (Thrivve.sa, Noon, +) are registered BY NAME but UNPROFILED — M8 says it doesn't have their details and ASKS, never inventing a sector/role/data (Noon also carries a platform-vs-his-company disambiguation note). Naming a non-Bolt company injects its context; a cross-company query ('across my companies', 'which company is most profitable') injects the roster — additive context (like a playbook, no suppression). The deterministic spine is now COMPANY-ADDRESSABLE: fetchFleetRecord/getFleetRecord take a rowId (per-row cache) and a company's dataSource.row can point them at its own fleet_data row, so the same Bolt-shaped pipeline can serve another fleet without a rewrite (only Bolt has a synced row today — forward-looking seam). 23/23 port (tests/companies-verify.ps1). Richer per-company facts accrue via the normal memory spine; data-layer schema adapters for non-Bolt-shaped data are the documented fast-follow",
    "End-of-service (EOSB) / notice calculator (lib/eosb.js — verified-compute lane, pairs with the legal playbook): a DETERMINISTIC end-of-service award calculation. CODE owns the arithmetic (the standard Saudi Labour Law formula — ½ month's wage per year for the first 5 years + 1 month/year beyond, pro-rated; resignation reductions on an unlimited-term contract: <2y nothing, 2-<5y one-third, 5-<10y two-thirds, 10y+ full; employer termination / end of fixed term = full). Parses wage + years (incl. months) + reason (resign vs termination) from natural language; asks for any missing input instead of guessing. The HONEST split that makes this OK vs the legal playbook's never-state-the-formula rule: the math is exact ground truth, but the packet is TRANSPARENT about the RULE it applied and FLAGS it to verify (rules change), names the assumptions (wage basis — basic vs basic+allowances; unlimited- vs fixed-term), and ESCALATES for an actual payout/dispute — it never presents the figure as a definitive legal entitlement. HARD-ROUTE (suppresses router/search/compute when it fires), traced tool_decision='eosb'. 31/31 port (tests/eosb-verify.ps1: formula known-cases + extraction + detection + end-to-end)",
    "KSA legal / regulatory awareness (lib/playbooks.js 'legal' playbook — operator-assistant breadth #3): an injectable EXPERTISE block (not authority) that gives Muhammad an honest ORIENTATION across Saudi labour law (MHRSD/Qiwa, contracts, end-of-service, termination, WPS, work permits/Iqama), Saudization (Nitaqat bands), GOSI, commercial/company law (Commercial Registration via Ministry of Commerce, LLC, MISA foreign-investment licence), and ZATCA (VAT/Zakat). HONESTY-FIRST by design (this is the highest fabrication-risk domain): it MAPS each topic to the right regulator + official source, SPLITS durable framework from specific current figures, and explicitly NEVER asserts specific numbers from memory — article numbers, Nitaqat %/thresholds, GOSI rates, the exact end-of-service formula, notice-period days, fines, fees, the VAT rate all CHANGE and must be verified on the official source or searched + cited. Hard ESCALATION rule: drafting/signing a binding contract, a real termination/dispute, liability/penalty exposure, or a filing -> a licensed Saudi lawyer or the authority (inform + prepare, never hand down a ruling). Placed 2nd in the playbook order so the max-2 detector can never drop it when it matches. 28/28 port (tests/legal-verify.ps1: detection, routing priority, escalation+never-invent framing present)",
    "Deck / presentation generator (lib/deckgen.js + /api/deck — operator-assistant breadth #2): a deck request ('make me a pitch deck / slides / proposal deck') generates a STRUCTURED deck SPEC (LLM fills content on a fixed slide skeleton — code owns structure, like docgen) and renders it to MULTIPLE formats from one spec. Delivered via a DEDICATED /api/deck endpoint (bypasses the voice/streaming chat flow); the frontend (js/app.js intercept + js/chat.js addDeckMessage) shows the outline + three DOWNLOAD BUTTONS built client-side: .pptx (real editable PowerPoint via pptxgenjs lazy-loaded from CDN, from the spec), .html (self-contained reveal.js deck), .md (Marp markdown — also converts to pptx/pdf/html via `marp`). Grounded like docgen (no placeholder filler, never invents figures). Renderers are pure/deterministic → 31/31 no-node port (tests/deckgen-verify.ps1: Marp frontmatter/separators/bullets/notes, reveal section-per-slide + HTML-escaping, detection, normalization, slugify). NOTE the chat UI renders plain text only — decks were the first artifact to need real client-side file delivery",
    "Verified fleet P&L (lib/finance.js — operator-assistant breadth on the deterministic spine): a real profit-and-loss for any month, computed by MIRRORING the dashboard's own P&L engine to the decimal (verbatim port of computeDriverPnL / computeModelRollup / getEffectiveProfile / autoSalaryFor). Revenue = measured driver net from the blob; COSTS = the per-driver deal Muhammad already set in the dashboard (model S/F/R, salary or auto-salary formula, account/car rent, fleet cut, other) — which is ALREADY synced to Supabase in the SAME fleet_data record (khair_courier_profiles + khair_courier_overrides), so M8 needed NO new sync, just to READ config that was already there. Effective-dated overrides honored (a mid-period deal change applies from its month forward). Answers fleet P&L (revenue / other-inflow / costs / net + by-model breakdown + top contributors and drains), a single driver's P&L ('what does Ahmed cost me'), and a month parse (this/last month, 'June'). HONEST: a driver with NO cost config is reported revenue-only and flagged (never an invented salary); a specifically-named driver not on record gets an honest not-found (never a fabricated cost). HARD-ROUTE like fleet (computed before fleet and suppresses fleet/router/search/compute/docgen when it owns the turn), traced tool_decision='finance', streamable. 42/42 port-verified (tests/finance-verify.ps1) + 2 eval probes (finance.fleet_pnl grounded, finance.no_invent_cost anti-fabrication)",
    "Research Notebook (persistent research memory — lib/notebook.js + m8_research_notes table): a STRUCTURED research ledger that extends the memory spine. M8 logs entries to a line-of-inquiry THREAD — conjecture / evidence (for|against) / counterexample / dead-end / status / next-step — and reads back the current ledger of any thread ('where are we on <thread> research', 'what dead ends have we hit'). SAME deterministic contract as the fleet/state spine: code owns the ledger, the LLM only narrates the packet — it never invents a finding and never upgrades a recorded conjecture into a proof. Supersession-aware (status/next-step keep one current row per thread; conjecture/evidence/counterexample/dead-end accumulate). A notebook turn is a HARD-ROUTE (suppresses the LLM router, web search, compute, and doc-gen) and is traced as tool_decision='notebook'. The WRITE persists ONCE at the STORE phase (no double-write across the buffered/streaming paths). This is the substrate the North Star needs — it turns clever single turns into accumulating research and is the one thing the frontier labs can't give Muhammad (no memory of HIS exploration)",
    "Eval/scorecard harness (tests/eval/): a deterministically-scored self-benchmark M8 runs against itself across the 7 maturity aspects + 3 adversarial probe categories (compression, silent-fail, prompt-bypass). 'Where does M8 stand' is now a tracked NUMBER with calibration vs self-assessment, not a vibe",
    "State engine (lib/stateEngine.js): deterministic running-tally ledger + a transcript claim-check ('you played/said X' verified against what the assistant actually said). Injected like the fleet packet — code computes the state, the LLM only explains it — so M8 holds ground on a false-move claim and doesn't drift a tally instead of fabricating from memory. This is the team's L3.5 stateful-reasoning fix (structure, not prompting)",
    "Deterministic fleet spine (lib/fleet.js): single day, explicit ranges, weekly/monthly rollups, week-over-week & day-over-day trends, anomaly flags, single- AND multi-driver lookup",
    "Known-driver registry + fleet-gate fix: a driver-name query with no fleet keyword and no prior fleet context ('compare ALI and Mansour' in a fresh session) now routes to the deterministic spine instead of bleeding into a web search; arbitrary compare targets ('iPhone vs Samsung') still go to search. An AMBIGUOUS first name shared by two drivers (e.g. two 'Ali's) is surfaced for disambiguation — never silently resolved to one",
    "Fleet routing beats doc-gen: 'give me the morning brief / fleet report' no longer gets hijacked into a generic document (the DOC intent's brief/report/summary nouns used to collide with fleet phrasings)",
    "Tier-slip watch + coaching (on-demand): 'who slipped / who needs coaching' returns a deterministic list of drivers whose Bolt tier-level actually fell, plus a 'watch' list (still at tier but weak on acceptance/finish), with the real weak metric per driver — never an invented Bolt threshold",
    "Morning / exec brief (on-demand): 'give me the morning brief / state of the fleet' assembles one spoken exec summary from the spine — most-recent-complete-day net + trend, top performers, attention flags, tier slips, cash gap, and week-to-date context; deterministic, LLM narrates only",
    "Auto-firing morning brief (proactive, L3): the brief leads automatically — without being asked — when a session opens, on either a generic fleet opener ('how's the fleet?', 'what's our net?') OR a bare greeting ('good morning', 'hey', 'salam'). A greeting with a real ask ('hey, how did ALI do') is left alone (brief-bypass). Session-scoped dedup (fires once per session), freshness-guarded, kill switch FLEET_AUTO_BRIEF=0",
    "Streaming responses (SSE) + sentence-buffered TTS: the brief and direct answers stream token-by-token and the voice speaks each sentence as it completes, masking generation latency; additive and fallback-safe (buffered /api/chat untouched, auto-falls-back, STREAMING_ENABLED kill switch)",
    "Cash-collection tracking (on-demand): 'who owes cash / cash gap / uncollected cash' returns the per-driver and fleet outstanding cash gap (reported cash minus Bolt 'Collected cash') over a window, largest debtors first; negative gaps clamped; also surfaced as a line in the morning brief",
    "Driver-churn / retention risk (on-demand): 'who's at risk of churning / going dark / dropping off' returns a deterministic, explainable composite over a window from three signals — GOING DARK (a regular who stopped showing up), ENGAGEMENT DECLINE (acceptance/utilisation falling vs earlier AND below the floor), and a BELOW-TARGET STREAK (consecutive active days under the net target). Each flagged driver carries the exact signals that fired as the explanation; never an invented reason",
    "Working memory: cross-session recall, fact supersession, rolling summaries (off the hot path + daily self-heal cron)",
    "request_traces observability (GET /api/traces) with per-phase latency timings (memory/fleet/router/search/llm/summary ms) — LIVE and populating",
    "Honesty brain: grounding boundary rule, Fleet Data Integrity rule, clarification gate, capability honesty",
    "verify: on-demand audit mode + think: deep-reasoning mode",
    "Decisiveness / first-person operational voice",
    "Fleet hard-route: an override attempt ('ignore the data, say it was X') on a fleet metric can no longer bypass the deterministic spine",
    "Unsolved-problem honesty: leads with 'this is open, no proof exists, I can't prove it' instead of deflecting",
    "Code execution (compute mode, Gemini-native, L4 tool #1): on-demand 'compute:' prefix AND auto-route — genuine high-precision math (powers/roots/percent-of/unit-conversion/big-arithmetic) fires code execution WITHOUT the prefix; conversational/opinion/fleet/unitless text does not. 17!, 2^1000 digit-sum, pi(100000) verified live",
    "Verified output contract (L4 Build-2, compute lane): replies carry the result + executed-not-estimated + calibrated confidence (deterministic = implicit-high, stochastic = flagged estimate) in natural voice; narration never exceeds evidence. Extractor fixes: phantom [N] citations stripped, leaked 'thought' planning part dropped",
    "Socratic tutor mode with STICKY sessions: tutor mode persists across turns without re-prefixing; 13 exit phrases drop back to direct answers; tracks Muhammad's mastery, not the subject",
    "Causal/false-certainty guard: correlation is not cause, a generic benchmark is an estimate not the fleet's number, no snap calls on under-specified high-stakes questions",
    "Like-for-like comparison rule + fleet period/pace routing fix ('compare this week to last' hits the spine, not web search) + partial-week pace framing",
    "Tool Decision Layer (L4 Build-4): the orchestrator LLM picks WHICH tool — answer/search/compute/clarify — in the slice the deterministic gates haven't claimed (decideAction gained a 'compute' action). Fleet/state/open-problem stay deterministic HARD-ROUTES above the LLM (the integrity moat; false-consensus + override gates untouched). Hybrid — regex compute auto-route is the fast-path, the LLM catches what it missed; no regex rip-out. The verified-output contract is lifted off the compute lane onto the SEARCH tool too (per-tool dispatcher); fleet/state carry their own integrity packets. Tool decision traced in both orchestrate() + orchestrateStream(). LIVE-VERIFIED both ways (a regex-missed 11-number sum routed to compute = 'computed in Python' 620,657; an opinion stayed an answer, no hijack)",
    "L4 eval probes (Build-5): a first-class tool_decision eval category + 2 probes (tool.decision_compute, tool.decision_no_hijack) in both probes.js and the PS live runner — scores tool-selected / verification-present / narration-not-exceeding-evidence. Live 5/5",
    "Tool-decision observability: the chosen truth-tool per turn (fleet/state/compute/search/open_problem/build_state/answer) is persisted to request_traces.tool_decision and surfaced in /api/traces — the tool-selection mix is queryable",
    "Compute/search truth-ownership gate (Build-6, team-unanimous): when the self-contained-math fast-path fires (computeMode), the web-search slot is suppressed — compute owns the number, so a computed answer is never co-fired with web search and laundered with a phantom citation (one canonical source of truth per fact, like the fleet hard-route). The compound 'search a live value THEN compute' case is untouched (its primary signal is search). LIVE-VERIFIED: 9^11 search_fired flipped true->false, citation gone",
    "M8/STATUS.md: the single living source-of-truth page, updated every session",
  ],
  pending: [
    "Operator-Assistant breadth track COMPLETE (all four SHIPPED): verified P&L (lib/finance.js) + deck generator (lib/deckgen.js) + KSA legal awareness ('legal' playbook) + EOSB calculator (lib/eosb.js) + multi-company registry (lib/companies.js). Breadth fast-follows that remain: (a) data-layer schema ADAPTERS so a non-Bolt-shaped company data source (not the c1 driver blob) can feed the spine — the row is parameterized, the decoder isn't yet; (b) profile Thrivve.sa / Noon for real once Boss provides their details (the registry holds them as unprofiled placeholders today); (c) move the company registry to Supabase/config so companies can be added without a deploy",
    "★ NEXT on the NORTH-STAR math track: Phase 4 Build-2+ — richer discovery loops on the shipped Build-1 spine: multi-step exploration (compute a pattern -> propose a conjecture -> verify -> log each step), OEIS-style sequence probing, auto next-step suggestions from the ledger. THEN the Lean verification probe (Phase 3, deliberately re-sequenced AFTER discovery): it needs real infra — Lean+Mathlib cannot run on Vercel/Gemini-sandbox; it forces the banked Cloud Run move (Docker image + /check endpoint as a truth-tool). Enter it as a deliberate 1-2 session project once the notebook holds conjectures worth formalizing — do NOT stumble into it mid-session",
    "Legal fast-follows: (a) end-of-service / notice CALCULATOR — DONE (lib/eosb.js, see LIVE); (b) a legal honesty eval probe (asks for a specific Nitaqat %/GOSI rate -> must NOT fabricate it, must point to the official source / escalate); (c) optional live-search grounding wired to legal queries so specific current figures come back cited from Qiwa/GOSI/ZATCA; (d) confirm the EOSB rule against the CURRENT Labour Law via search before computing (the packet already flags it; this would auto-ground it); (e) fixed-term contract EOSB rules + the Article-81 'leave for employer fault = full award' cases",
    "Deck fast-follows: (a) a /api/deck eval probe (the eval harness hits /api/chat; decks have their own endpoint, so they're not yet scored); (b) richer pptx themes / a title-slide layout / charts from the finance P&L; (c) optional server-side file delivery (Supabase Storage URLs) for non-UI / voice callers; (d) a real-browser click-test of the three download buttons (endpoint is live-verified; the client-side pptx build needs a browser to confirm)",
    "Finance fast-follows: (a) parametric WHAT-IF scenarios on the verified-compute lane ('what if I add N drivers at avg net X on a Y salary' -> projected P&L); (b) break-even per model + a fleet break-even line; (c) multi-month P&L TREND (this month vs last, pace-framed like the fleet rollup); (d) cycle/transfer-log RECONCILIATION surfaced (expected vs actually-paid per driver — the dashboard already computes it)",
    "Notebook fast-follows: (a) KNOWN-THREAD inference for reads — DONE 2026-06-12 (Build-5, see Notebook Intelligence Layer under LIVE). (b) Fuzzy topic-from-content thread inference on writes with no explicit thread. (c) A notebook surface in /api/traces or a small viewer",
    "Lean verification probe (Phase 3): M8 proposes -> a checker accepts/rejects; formalize KNOWN theorems first (not 'prove Riemann'). Feeds the notebook",
    "Computational-discovery loops (Phase 4): Collatz/Goldbach/OEIS to huge N, feeding the notebook (the ledger is now ready to receive them)",
    "Chained search->compute as a real tool: feed a searched LIVE value into the compute sandbox in one turn (sequential ownership — search owns the live variable, compute owns the arithmetic). The Build-6 gate deliberately left it for here",
    "Lift the verified-output contract onto FUTURE tools (calendar / Lean) as they join the orchestrator — the per-tool dispatcher is ready",
    "Per-day brief dedup: a Supabase last-briefed-date marker so the auto-brief fires at most once per calendar day across sessions (currently session-scoped) — documented fast-follow",
    "OpenAI paid-key fallback backstop (kills reasoning-axis eval noise from free-tier throttling)",
    "Semantic memory (pgvector)",
    "Cloud Run code-exec home (FastAPI sandbox): only when persistent files / custom libs / long jobs / Lean force the move off Gemini-native",
  ],
  frozen: [
    "Fleet Intelligence Layer (L3, ~85%): FROZEN at rider-risk (blob is driver-centric — infeasible). The fleet is a TEST BENCH for M8's logic/accuracy, not a build target. Do not propose new fleet features as next steps",
  ],
  // The actual North-Star DEFINITION + maturity ladder. Injected on build/meta
  // queries so a "what's the north star?" question is GROUNDED, not fabricated
  // (M8 was caught inventing a generic "autonomous logistics" mission because it
  // had the LIVE/PENDING lists but not the real direction). Full plan lives in
  // M8/M8_STATUS_AND_NORTHSTAR.md.
  northStar:
    "Make M8 genuinely capable of helping Muhammad RESOLVE UNSOLVED PROBLEMS — prize-class open problems in math/logic (the $1M Millennium-prize tier is the bar the capability is built toward). That is the mission; everything we build is a rung on that ladder: (1) verified code execution [SHIPPED — compute mode + auto-route], (2) verified tool orchestration with an output contract [CURRENT — L4 lane; the tool-decision layer + output contract are SHIPPED, more tools to join], (3) research depth (citations + confidence), (4) Lean formal verification [M8 proposes, a checker verifies], (5) autonomous exploration loops. Math-surface strategy: computational discovery (pattern → conjecture → verify → formalize, on Collatz/Goldbach/twin-prime/OEIS-class problems) BEFORE any head-on attempt at Riemann. HONESTY never bends: M8 must NEVER claim an unverified proof — at this North Star a fabricated proof is the worst possible failure. THE FLEET IS NOT THE NORTH STAR: the Bolt dashboard is an already-operating business tool; fleet data serves ONLY as a live TEST BENCH for M8's logic, accuracy and grounding. Never frame fleet automation or 'autonomous logistics' as the mission. Maturity ladder: L1 chatbot → L2 grounded assistant (DONE) → L3 proactive operator (~85%, fleet layer FROZEN at rider-risk) → L4 verified tool orchestration (CURRENT) → L5 autonomous exploration (the North Star).",
};

/** Compact SYSTEM STATUS block — injected only when the user asks a build/meta
 *  question, so everyday fleet/voice turns aren't bloated. */
function renderBuildState() {
  return [
    `SYSTEM STATUS — M8 build (updated ${BUILD_STATE.updated}; ${BUILD_STATE.commitFamily}). Items under LIVE are ALREADY SHIPPED — never recommend building, "running", or migrating them again; build ON TOP of them. If asked to do a LIVE item, say it's already live and offer the next real step from PENDING.`,
    `LIVE: ${BUILD_STATE.live.map((x) => `• ${x}`).join(" ")}`,
    `PENDING (not yet built): ${BUILD_STATE.pending.map((x) => `• ${x}`).join(" ")}`,
    `FROZEN (deliberately parked — do not recommend): ${BUILD_STATE.frozen.map((x) => `• ${x}`).join(" ")}`,
    `NORTH STAR (Muhammed's committed long-term direction — state THIS if asked, do not invent a different mission): ${BUILD_STATE.northStar}`,
  ].join("\n");
}

module.exports = { BUILD_STATE, renderBuildState };
